# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AnimationDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimationDemo
 pod 'SnapKit', '~> 5.0.0'
end
